<?php

return [
    /**
     * you can add a new Menus Class that generated by tomato:menu MENU_NAME here to register
     * the menu to the tomato-admin menu system
     */
    "menus" => [
        //
    ]
];
